import { WakfuStats } from "src/wakfu/types/action";
import type { TWakfuDescription } from "src/wakfu/types/description";

export const wakfuStatsLabels: Record<WakfuStats, TWakfuDescription> = {
  [WakfuStats.PV]: {
    fr: "PV",
    en: "HP",
    es: "PV",
    pt: "PV",
  },
  [WakfuStats.PW]: {
    fr: "PW",
    en: "WP",
    es: "PW",
    pt: "PW",
  },
  [WakfuStats.PA]: {
    fr: "PA",
    en: "PA",
    es: "PA",
    pt: "PA",
  },
  [WakfuStats.PM]: {
    fr: "PM",
    en: "PM",
    es: "PM",
    pt: "PM",
  },
  [WakfuStats.Mastery]: {
    fr: "Maîtrise Élémentaire",
    en: "Elemental Mastery",
    es: "Maestría Elemental",
    pt: "Maestria Elemental",
  },
  [WakfuStats.MasteryFire]: {
    fr: "Maîtrise Feu",
    en: "Fire Mastery",
    es: "Maestría Fuego",
    pt: "Maestria Fogo",
  },
  [WakfuStats.MasteryEarth]: {
    fr: "Maîtrise Terre",
    en: "Earth Mastery",
    es: "Maestría Tierra",
    pt: "Maestria Terra",
  },
  [WakfuStats.MasteryWater]: {
    fr: "Maîtrise Eau",
    en: "Water Mastery",
    es: "Maestría Agua",
    pt: "Maestria Água",
  },
  [WakfuStats.MasteryAir]: {
    fr: "Maîtrise Air",
    en: "Air Mastery",
    es: "Maestría Aire",
    pt: "Maestria Ar",
  },
  [WakfuStats.Resistance]: {
    fr: "Résistance Élémentaire",
    en: "Elemental Resistance",
    es: "Resistencia Elemental",
    pt: "Resistência Elemental",
  },
  [WakfuStats.ResistanceFire]: {
    fr: "Résistance Feu",
    en: "Fire Resistance",
    es: "Resistencia Fuego",
    pt: "Resistência Fogo",
  },
  [WakfuStats.ResistanceWater]: {
    fr: "Résistance Eau",
    en: "Water Resistance",
    es: "Resistencia Agua",
    pt: "Resistência Água",
  },
  [WakfuStats.ResistanceEarth]: {
    fr: "Résistance Terre",
    en: "Earth Resistance",
    es: "Resistencia Tierra",
    pt: "Resistência Terra",
  },
  [WakfuStats.ResistanceAir]: {
    fr: "Résistance Air",
    en: "Air Resistance",
    es: "Resistencia Aire",
    pt: "Resistência Ar",
  },
  [WakfuStats.CriticalRate]: {
    fr: "Coup Critique",
    en: "Critical Hit",
    es: "Golpe Crítico",
    pt: "Golpe Crítico",
  },
  [WakfuStats.Initiative]: {
    fr: "Initiative",
    en: "Initiative",
    es: "Iniciativa",
    pt: "Iniciativa",
  },
  [WakfuStats.Dodge]: {
    fr: "Esquive",
    en: "Dodge",
    es: "Esquivar",
    pt: "Esquiva",
  },
  [WakfuStats.Control]: {
    fr: "Contrôle",
    en: "Control",
    es: "Control",
    pt: "Controle",
  },
  [WakfuStats.Block]: {
    fr: "Parade",
    en: "Block",
    es: "Bloquear",
    pt: "Bloquear",
  },
  [WakfuStats.Range]: {
    fr: "Portée",
    en: "Range",
    es: "Alcance",
    pt: "Alcance",
  },
  [WakfuStats.Lock]: {
    fr: "Tacle",
    en: "Lock",
    es: "Tacle",
    pt: "Tacle",
  },
  [WakfuStats.Willpower]: {
    fr: "Volonté",
    en: "Willpower",
    es: "Voluntad",
    pt: "Vontade",
  },
  [WakfuStats.CriticalMastery]: {
    fr: "Maîtrise Critique",
    en: "Critical Mastery",
    es: "Maestría Crítica",
    pt: "Maestria Crítica",
  },
  [WakfuStats.CriticalResistance]: {
    fr: "Résistance Critique",
    en: "Critical Resistance",
    es: "Resistencia Crítica",
    pt: "Resistência Crítica",
  },
  [WakfuStats.BackMastery]: {
    fr: "Maîtrise Dos",
    en: "Rear Mastery",
    es: "Maestría Espalda",
    pt: "Maestria Costas",
  },
  [WakfuStats.BackResistance]: {
    fr: "Résistance Dos",
    en: "Rear Resistance",
    es: "Resistencia Espalda",
    pt: "Resistência Costas",
  },
  [WakfuStats.MeleeMastery]: {
    fr: "Maîtrise Mêlée",
    en: "Melee Mastery",
    es: "Maestría Cuerpo a Cuerpo",
    pt: "Maestria Corpo a Corpo",
  },
  [WakfuStats.DistanceMastery]: {
    fr: "Maîtrise Distance",
    en: "Ranged Mastery",
    es: "Maestría A Distancia",
    pt: "Maestria à Distância",
  },
  [WakfuStats.ArmorGiven]: {
    fr: "Armure Donnée",
    en: "Armor Given",
    es: "Armadura Dada",
    pt: "Armadura Dada",
  },
  [WakfuStats.ArmorReceived]: {
    fr: "Armure Reçue",
    en: "Armor Received",
    es: "Armadura Recibida",
    pt: "Armadura Recebida",
  },
  [WakfuStats.HealingMastery]: {
    fr: "Maîtrise Soins",
    en: "Healing Mastery",
    es: "Maestría en Curación",
    pt: "Maestria em Cura",
  },
  [WakfuStats.BerserkMastery]: {
    fr: "Maîtrise Berserk",
    en: "Berserk Mastery",
    es: "Maestría Berserk",
    pt: "Maestria Berserk",
  },
  [WakfuStats.FinalDamage]: {
    fr: "Dommages infligés",
    en: "Damage Dealt",
    es: "Daño Infligido",
    pt: "Dano Infligido",
  },
  [WakfuStats.FinalHealing]: {
    fr: "Soins réalisés",
    en: "Healing Done",
    es: "Curación Realizada",
    pt: "Cura Realizada",
  },
  [WakfuStats.Wisdom]: {
    fr: "Sagesse",
    en: "Wisdom",
    es: "Sabiduría",
    pt: "Sabedoria",
  },
  [WakfuStats.Prospection]: {
    fr: "Prospection",
    en: "Prospection",
    es: "Prospección",
    pt: "Prospeção",
  },
  [WakfuStats.IndirectDamages]: {
    fr: "Dommages Indirects",
    en: "Indirect Damages",
    es: "Daños Indirectos",
    pt: "Danos Indiretos",
  },
  [WakfuStats.HealingReceived]: {
    fr: "Soins Reçus",
    en: "Healing Received",
    es: "Curación Recibida",
    pt: "Cura Recebida",
  },
  [WakfuStats.Armor]: {
    fr: "Armure",
    en: "Armor",
    es: "Armadura",
    pt: "Armadura",
  },
};
